# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.20.0"

default_platform :mac

platform :mac do
  before_all do
    ENV["SLACK_URL"] = ENV["CMDJIRA_SLACK_URL"]
    
    
  end

  desc "Deploy a new version to the Github"
  lane :release do
    gym(output_directory: "./build")

    version = sh("git rev-list HEAD --count").chomp
    zip(path: "./build/cmdjira", output_path: "../build/cmdjira-#{version}.zip"
)
    
    description = prompt(text: "Please enter a changelog (make sure to rephrase changes to make it easy to understand, and remove non-important changes that don't affect the end-user): ",
                         multi_line_end_keyword: "END")

    set_github_release(
      repository_name: "Szaq/cmdjira",
      name: version,
      tag_name: version,
      description: description,
      is_draft: false,
      upload_assets: ["./build/cmdjira-#{version}.zip"]
    )

    sh "rm -R ../build"

    slack(
       message: "New version available: #{version}. Description:\n#{description} "
     )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
